repos:
- repo: local
  hooks:
  - id: lintr
    name: lintr
    entry: Rscript -e "if(length(lintr::lint_package()) > 0) stop('Linting failed')"
    language: system
    files: \\.R$
    pass_filenames: false
    stages: [commit]
  - id: roxygenize
    name: roxygenize
    entry: Rscript -e "roxygen2::roxygenize()"
    language: system
    files: \\.R$
    pass_filenames: false
    stages: [commit]
  - id: r-tests
    name: R package tests
    entry: Rscript -e "
      Sys.setenv(
        AWS_ACCESS_KEY_ID_DEV='mock_dev_key',
        AWS_SECRET_ACCESS_KEY_DEV='mock_dev_secret',
        AWS_ACCESS_KEY_ID_PROD='mock_prod_key', 
        AWS_SECRET_ACCESS_KEY_PROD='mock_prod_secret'
      );
      if(any(sapply(devtools::test(), function(x) length(x$failed)) > 0)) stop('Tests failed')
      "
    language: system
    files: \\.R$
    pass_filenames: false
    stages: [commit]
  - id: package-check
    name: R CMD check
    entry: Rscript -e "
      check_result <- devtools::check(args = c('--no-manual'), error_on = 'never');
      if(length(check_result$errors) > 0) stop('Package check failed')
      "
    language: system
    files: \\.R$
    pass_filenames: false
    stages: [push]

# Additional hooks for general code quality
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: \\.Rd$
  - id: end-of-file-fixer
    exclude: \\.Rd$
  - id: check-yaml
  - id: check-added-large-files
